// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plant_BiologyEducation.Data;

#nullable disable

namespace Plant_BiologyEducation.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.AccessBookHistory", b =>
                {
                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Book_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Visited_Number")
                        .HasColumnType("int");

                    b.HasKey("User_Id", "Book_Id");

                    b.HasIndex("Book_Id");

                    b.ToTable("AccessBookHistories");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.AccessLessonHistory", b =>
                {
                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Lesson_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Visited_Number")
                        .HasColumnType("int");

                    b.HasKey("User_Id", "Lesson_Id");

                    b.HasIndex("Lesson_Id");

                    b.ToTable("AccessLessonHistories");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Book", b =>
                {
                    b.Property<Guid>("Book_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Book_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover_img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Book_Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Chapter", b =>
                {
                    b.Property<Guid>("Chapter_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Book_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chapter_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Chapter_Id");

                    b.HasIndex("Book_Id");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Lesson", b =>
                {
                    b.Property<Guid>("Lesson_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Chapter_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lesson_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Lesson_Id");

                    b.HasIndex("Chapter_Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.ManageBook", b =>
                {
                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Book_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("User_Id", "Book_Id");

                    b.HasIndex("Book_Id");

                    b.ToTable("ManageBooks");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.ManageChapter", b =>
                {
                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Chapter_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("User_Id", "Chapter_Id");

                    b.HasIndex("Chapter_Id");

                    b.ToTable("ManageChapters");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.ManageLesson", b =>
                {
                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Lesson_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("User_Id", "Lesson_Id");

                    b.HasIndex("Lesson_Id");

                    b.ToTable("ManageLessons");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Plant_Bilogy_Animals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetailsInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plant_Biology_Animals");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.User", b =>
                {
                    b.Property<Guid>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.AccessBookHistory", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Book", "Book")
                        .WithMany("AccessHistories")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plant_BiologyEducation.Entity.Model.User", "User")
                        .WithMany("BookHistories")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.AccessLessonHistory", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Lesson", "Lesson")
                        .WithMany("AccessHistories")
                        .HasForeignKey("Lesson_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plant_BiologyEducation.Entity.Model.User", "User")
                        .WithMany("LessonHistories")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Chapter", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Lesson", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("Chapter_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.ManageBook", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Book", "Book")
                        .WithMany("ManagedBy")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plant_BiologyEducation.Entity.Model.User", "User")
                        .WithMany("ManagedBooks")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.ManageChapter", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Chapter", "Chapter")
                        .WithMany("ManagedBy")
                        .HasForeignKey("Chapter_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plant_BiologyEducation.Entity.Model.User", "User")
                        .WithMany("ManagedChapters")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.ManageLesson", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Lesson", "Lesson")
                        .WithMany("ManagedBy")
                        .HasForeignKey("Lesson_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plant_BiologyEducation.Entity.Model.User", "User")
                        .WithMany("ManagedLessons")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Book", b =>
                {
                    b.Navigation("AccessHistories");

                    b.Navigation("Chapters");

                    b.Navigation("ManagedBy");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Chapter", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("ManagedBy");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Lesson", b =>
                {
                    b.Navigation("AccessHistories");

                    b.Navigation("ManagedBy");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.User", b =>
                {
                    b.Navigation("BookHistories");

                    b.Navigation("LessonHistories");

                    b.Navigation("ManagedBooks");

                    b.Navigation("ManagedChapters");

                    b.Navigation("ManagedLessons");
                });
#pragma warning restore 612, 618
        }
    }
}
