// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plant_BiologyEducation.Data;

#nullable disable

namespace PlantBiologyEducation.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250722084247_InitialCreateDB")]
    partial class InitialCreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantBiologyEducation.Entity.Model.AccessBiology", b =>
                {
                    b.Property<Guid>("AccessBiology_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Oject_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("VisitedNumber")
                        .HasColumnType("integer");

                    b.HasKey("AccessBiology_Id");

                    b.HasIndex("Oject_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("AccessBiologies");
                });

            modelBuilder.Entity("PlantBiologyEducation.Entity.Model.AccessBook", b =>
                {
                    b.Property<Guid>("AccessBook_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Book_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("VisitedNumber")
                        .HasColumnType("integer");

                    b.HasKey("AccessBook_Id");

                    b.HasIndex("Book_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("AccessBooks");
                });

            modelBuilder.Entity("PlantBiologyEducation.Entity.Model.AccessLesson", b =>
                {
                    b.Property<Guid>("AccessLesson_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Lesson_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("VisitedNumber")
                        .HasColumnType("integer");

                    b.HasKey("AccessLesson_Id");

                    b.HasIndex("Lesson_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("AccessLessons");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Book", b =>
                {
                    b.Property<Guid>("Book_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Book_Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cover_img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Book_Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Chapter", b =>
                {
                    b.Property<Guid>("Chapter_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Book_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Chapter_Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Chapter_Id");

                    b.HasIndex("Book_Id");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Lesson", b =>
                {
                    b.Property<Guid>("Lesson_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Chapter_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Lesson_Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Lesson_Id");

                    b.HasIndex("Chapter_Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.User", b =>
                {
                    b.Property<Guid>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("resetToken")
                        .HasColumnType("text");

                    b.HasKey("User_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Plant_Biology_Animals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AverageLifeSpan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiscoveredAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExtinct")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecieType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Plant_Biology_Animals");
                });

            modelBuilder.Entity("PlantBiologyEducation.Entity.Model.AccessBiology", b =>
                {
                    b.HasOne("Plant_Biology_Animals", "Oject")
                        .WithMany()
                        .HasForeignKey("Oject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plant_BiologyEducation.Entity.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantBiologyEducation.Entity.Model.AccessBook", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Book", "Book")
                        .WithMany()
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plant_BiologyEducation.Entity.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantBiologyEducation.Entity.Model.AccessLesson", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("Lesson_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plant_BiologyEducation.Entity.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Chapter", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Lesson", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("Chapter_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Plant_Biology_Animals", b =>
                {
                    b.HasOne("Plant_BiologyEducation.Entity.Model.Lesson", "Lesson")
                        .WithMany("RelatedSpecies")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Book", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Chapter", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Plant_BiologyEducation.Entity.Model.Lesson", b =>
                {
                    b.Navigation("RelatedSpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
